### ISSUE TITLE
Implementa DELETE /api/tweets/{id}

### ISSUE THREAD

**Issue by sambrista** [Deg42/tweetfony#10]

**Comment by sambrista** [comment]
Al borrar el recurso debes devolver una respuesta vacía (null) con código HTTP 204 (no content).

En las APIs REST hay que procurar que las operaciones sean lo más simples posible, y usar correctamente los códigos de respuesta HTTP. De la forma en la que lo haces estás borrando el registro, pero además estás creando una lista con todos los tweets / usuarios y devolviéndola. Eso es algo que podría venirle bien al usuario, pero no es necesario y añade complejidad.

**Comment by Deg42** [comment]
Resuelto

**Comment by sambrista** [comment]
Comprobado.
